apiVersion: v1
kind: Namespace
metadata:
  name: lab4
  annotations:
    resourceQuota: lab4-quota

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: lab4-quota
  namespace: lab4
spec:
  hard:
    pods: 5
    requests.cpu: "1000m"
    requests.memory: "1Gi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restrictednginx
  namespace: lab4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restrictednginx
  template:
    metadata:
      labels:
        app: restrictednginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
